### PR TITLE
Create foo.js

### PR DESCRIPTION
**Pull request by danielkcz**

### CODE REVIEW

**Comment by creyD** [comment]
It worked! :)

**Comment by danielkcz** [comment]
Oh wow, it actually worked now 🎉

**Comment by danielkcz** [comment]
Thanks a lot, friend. This will help a lot. We are kinda sick of husky and each commit to be so slow because of Prettier.

**Comment by creyD** [comment]
I will clean up a couple of things and release a version 2.1 with this bugfix in a few days!

You are very welcome! I am glad I could help!

**Comment by danielkcz** [comment]
Wait, but why is that check marked as pending?

**Comment by creyD** [comment]
Seems buggy, probably something to do with the actions being pretty new?

**Comment by danielkcz** [comment]
I am thinking, won't it kinda go into an endless loop? When a trigger is on any update to PR and the action commits here, it will trigger again... Perhaps they have some protection for that and that's why it's pending.

**Comment by creyD** [comment]
No, GitHub Actions provide a mechanism against that.

**Comment by danielkcz** [comment]
That's interesting. So they don't provide native means to commit & push, but there is a mechanism to prevent recursion. Not sure what to think about that 😆

**Comment by creyD** [comment]
Me neither x)

**Pull request merged**
