### PR TITLE
Potential Fix for Action Bug

### PR DESCRIPTION
**Pull request by creyD**
Potentially fixed the GitHub actions bug.

### CODE REVIEW

**Comment by creyD** [comment]
Looking good so far! This request was using the latest state of the actions repo, so the bug should be resolved!

**Comment by danielkcz** [comment]
Thanks a lot. Can you add some `src/foo.js` to the PR? Currently, the Prettier is not even run for anything so it does not try committing.

**Comment by danielkcz** [comment]
That's even weirder now, why is it trying to checkout master? 🤔 

Anyway, I am curious why does it need to fetch & checkout? Given that I have checkout action in the workflow, shouldn't it run prettier in that workspace and then just commit & push changes? I am not sure if workspace can be shared across actions like that.

**Comment by creyD** [comment]
Because it is a remote pull request and my branch is called master too. :|

GitHub Actions set up the environment really strange, because they don't expect you to commit or even push anything from the action.

Can you redo the run? I changed something in the action.

**Comment by creyD** [comment]
It states that there are no matching files...

**Comment by creyD** [comment]
This is because I accidentally checked out your master and ran prettier in it and not in the remote. I moved the commands now, but we can't manually redo the check because you only can do this when it fails!

**Comment by creyD** [comment]
Can you rerun your test on the other PR #1 ?

**Comment by danielkcz** [comment]
I will merge this and rebase #1

**Pull request merged**
